server:
  port: 8088

# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MS_02_2022_PEDIDOS
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
# Apache Kafka #
custom:
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: topic-orden-autorizacion
    topic-name-ce: topic-orden-credito-estandar
    group-id: group-id-autorizacion
    group-id-ce: group-id-orden-credito-estandar

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true